/****시퀀스******
SEQUENCE : DB에서 제공하는 자동채번 객체
생성 : CREATE SEQUENCE 시퀀스명;
삭제 : DROP SEQUENCE 시퀀스명;

시퀀스명.NEXVAL : 시퀀스 번호(값) 생성
시퀀스명.CURRVAL : 현재 시퀀스값 확인 (NEXVAL 한번이상 실행 후)


******************/
CREATE SEQUENCE "MADANG"."SEQUENCE1"
MINVALUE 1 MAXVALUE 9999999999999999999999999
INCREMENT BY 1
START WITH 1 CACHE 20 NOORDER NOCYCLE;
---------------------------------------
SELECT SEQUENCE1.NEXTVAL FROM DUAL; --새로운 번호 생성
SELECT SEQUENCE1.CURRVAL FROM DUAL; --현재 시퀀스 번호(마지막 번호)

SELECT * FROM BOOK ORDER BY BOOKID DESC;
SELECT MAX(BOOKID), NVL(MAX(BOOKID),0) + 1 FROM BOOK;

--시퀀스를 사용하는 방식
CREATE SEQUENCE SEQ_BOOK
START WITH 50 
INCREMENT BY 1
NOCACHE;

--BOOK테이블에 INSERT 작업, BOOKID 최대값 +1 사용
INSERT INTO BOOK
       (BOOKID, BOOKNAME, PUBLISHER, PRICE)
VALUES ((SELECT NVL(MAX(BOOKID),0) +1 FROM BOOK),
        'MAX(BOOKID)+1', 'IT_BOOK', 20000);

INSERT INTO BOOK
       (BOOKID, BOOKNAME, PUBLISHER, PRICE)
VALUES (SEQ_BOOK.NEXTVAL,
        '시퀀스사용', 'IT_BOOK', 20000);

SELECT * FROM BOOK ORDER BY BOOKID DESC;












